title: 商商的自由小屋
description: Shangshang's free land.
author: 商叶华
github: https://github.com/thinwind
about: 我是一个勤劳的码农，现在主要从事Java应用开发
disqus_shortname: freeland

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

urls:
    - text: 关于我
      url: /about/
    - text: 我的Github
      url: https://github.com/thinwind
    - text: 分类浏览
      url: /projects/
    - text: RSS订阅
      url: /feed.xml

url: "https://thinwind.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist