title: 商商的自由小屋
description: Shangshang's free land.
author: Mr Shang
github: https://github.com/thinwind
about: 我是一个勤劳的码农，每天在技术的牧场辛勤劳作
myemail: niceshang[#]outlook.com

excerpt_separator: "\n\n\n"

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

urls:
    - text: 分类浏览
      url: /category/http
    - text: 关于我
      url: /about/
    - text: 我的Github
      url: https://github.com/thinwind
    - text: RSS订阅
      url: /feed.xml

url: "https://thinwind.github.io"
baseurl: ""
paginate: 4
per_page: 4
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist